[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Domain configuration
[context.production]
  environment = { URL = "https://www.midasdx.site" }

# Force HTTPS
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirect www to non-www
[[redirects]]
  from = "https://midasdx.site/*"
  to = "https://www.midasdx.site/:splat"
  status = 301
  force = true